spring:
  application:
    name: Spring-boot-microservice-with-config-server

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Aravindswamykosana/config-server-yamls"
          clone-on-start: true