spring.application.name=Spring-boot-microservice-with-front-end-integration
spring.datasource.url=jdbc:h2:file:C:/Users/ARAVIND/frontend;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update