server:
  port: 5000

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8001
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
