spring:
  application:
    name: loan-service
  boot:
    admin:
      client:
        url: "http://localhost:8080"


server:
  port: 9092

resilience4j:
  circuitbreaker:
    instances:
      loan-service:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
